// Thin-stroke Lucide icons per site domain. Modern, transparent, outline style.
import {
  Flame,
  Sparkles,
  Bike,
  Sailboat,
  Beef,
  TrendingUp,
  Car,
  Martini,
  Coffee,
  Trophy,
  Music,
  Wrench,
  Shirt,
  UtensilsCrossed,
  Dumbbell,
  Leaf,
  Sun,
  Gem,
  Swords,
  Bot,
  Footprints,
  Star,
  Mountain,
  Salad,
  PawPrint,
  Wine,
  Flower2,
  Zap,
  Compass,
  type LucideIcon,
} from "lucide-react";

export const SITE_ICONS: Record<string, LucideIcon> = {
  "barbecue.fan": Flame,
  "beauty.fan": Sparkles,
  "bike.fan": Bike,
  "boat.fan": Sailboat,
  "burger.fan": Beef,
  "capital.fan": TrendingUp,
  "car.fan": Car,
  "cocktail.fan": Martini,
  "coffee.fan": Coffee,
  "collector.fan": Trophy,
  "dance.fan": Music,
  "diy.fan": Wrench,
  "fashion.fan": Shirt,
  "gourmet.fan": UtensilsCrossed,
  "gym.fan": Dumbbell,
  "healthy.fan": Leaf,
  "lifestyle.fan": Sun,
  "luxury.fan": Gem,
  "martialarts.fan": Swords,
  "robotic.fan": Bot,
  "running.fan": Footprints,
  "tobe.fan": Star,
  "trek.fan": Mountain,
  "vegetarian.fan": Salad,
  "wildlife.fan": PawPrint,
  "wine.fan": Wine,
  "yoga.fan": Flower2,
  "sneaker.fan": Zap,
  "adventure.fan": Compass,
};

export function getSiteIcon(domain?: string | null): LucideIcon {
  if (domain && SITE_ICONS[domain]) return SITE_ICONS[domain];
  return Sparkles;
}
